spring.datasource.url=jdbc:postgresql://ep-curly-band-aoskeknb.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_zsv5AcyiuLg9

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=413F4428472B4B6250655368566D5970337336763979244226452948404D6351
app.jwt.expiration-milliseconds=900000
app.jwt.refresh-expiration-milliseconds=604800000
logging.level.org.springframework.security=DEBUG
